# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def pods
	pod 'Ruler'
end 

target 'YepShow' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YepShow
	pods

  target 'YepShowTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YepShowUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
